create option to render diff buttons
gusgard/react-native-swiper-flatlist pull request #63
Opened 2019-12-03 13:10 UTC by enieber

I migrate of react-native-swiper to this lib because performance in android, but I need adding buttons to change next or preview page, so this pr is for add option add leftButton and rightButton.

how to use:

```js
 <SwiperFlatList
        ref={ref => {
          this.flatListRef = ref
        }}
        horizontal
        pagingEnabled
        showPagination
        hasButton
        removeClippedSubviews
        scrollEnabled={false}
        data={this.state.onboardingSteps}
        index={this.state.step}
        paginationActiveColor={colors.primary}
        paginationDefaultColor={colors.gray}
        renderLeftButton={() => (
          <View style={style.containerButtonLeft}>
            <Button size="small" active onPress={this.prevStep.bind(this)}>
              <Icon name={'chevron-left'} size={30} color={colors.light} />
            </Button>
          </View>
        )}
        renderRightButton={() => (
          <View style={style.containerButtonRight}>
            <Button
              size="small"
              invalid={this.state.disableNext}
              active
              onPress={this.nextStep.bind(this)}
            >
              <Icon name={'chevron-right'} size={30} color={colors.light} />
            </Button>
          </View>
        )}
        renderItem={({ item, i }) => {
          return (
            <View>
               <Text>{item.name}</Text>
             </View>
          )
        }}
   />
```

2019-12-03 18:08 UTC, gusgard commented
Thanks, @enieber, I will review it at the weekend.

2020-12-01 15:10 UTC, gusgard requested changes
Thanks for this PR, could you check the comments?

2020-12-01 15:10 UTC, gusgard commented on src/components/Pagination/test.js
> -describe('pagination', () => {
Could we keep the tests?

2020-12-01 15:10 UTC, gusgard commented on src/components/Pagination/index.js
> +  if (hasButton) {
This should be done without the `hasButton`

```
{Array.from({ length: size }).map((_, index) => (
		{renderLeftButton?.()}
        <TouchableOpacity
          style={[
            styles.pagination,
            paginationStyleItem,
            paginationIndex === index
              ? { backgroundColor: paginationActiveColor }
              : { backgroundColor: paginationDefaultColor },
          ]}
          key={index}
          onPress={() => {
            scrollToIndex({ index });
          }}
        />
		{renderRightButton?.()}
      ))}
```

2020-12-01 15:15 UTC, gusgard commented on src/components/SwiperFlatList/SwiperFlatList.js
> +      renderRightButton,
This should follow the name conventions `paginationRenderLeft` and `paginationRenderRight`

2020-12-01 20:31 UTC, enieber commented
thanks @gusgard is code has many time ago, but I rewrite and update PR

2020-12-12 05:14 UTC, enieber commented on src/components/Pagination/test.js
> -describe('pagination', () => {
@gusgard the snapshot test is updated?

2021-05-03 21:58 UTC, closed without merging