Added `autoplayLoopAnimation` prop
gusgard/react-native-swiper-flatlist pull request #82
Opened 2020-11-17 12:26 UTC by curtismenmuir

- Added `autoplayLoopAnimation` prop to configure autoplay loop animation when end reached.
  - By default this value is set to `false` so original functionality remains (no animation when looping). 
  - Setting prop to true will enable scroll animation when looping.

2020-11-26 13:36 UTC, curtismenmuir commented
@gusgard Any thoughts on this change?

2020-11-30 17:25 UTC, curtismenmuir commented
Updated with extra functionality for `onPaginationPressed` prop. Thought behind this prop was to allow `autoplay` to be disabled after a user interacts with list (Manual Swipe or Pressing Pagination).

2020-12-01 15:03 UTC, gusgard requested changes
Thanks for this PR, it looks great 🙌

2020-12-01 15:03 UTC, gusgard commented on README.md
> +| onPaginationIndexSelected |                         -                         |        `func`         | Called after scroll to item when pagination index selected           |
Could we change this to `onPaginationSelectedIndex` and the description to `Executed when the user presses the pagination index, similar properties onChangeIndex`

2020-12-01 15:53 UTC, merged

2020-12-01 15:59 UTC, gusgard commented
Published with version `2.0.5` https://www.npmjs.com/package/react-native-swiper-flatlist